### ISSUE TITLE
Man Makefile Caractere Error Ubuntu 18.04

### ISSUE THREAD

**Issue by eliodilar** [jserot/caph#3] opened 2018-11-09 13:18 UTC
Héllo,

During compilation, there is an caractere error on SEd command on Pod to Latex conversion.
It seems that on line:
.pod.tex:
	@$(POD2TEX) 

the @sed command meet and error on the char during the .l to .tex conversion  

![caphmakepod](https://user-images.githubusercontent.com/44893881/48264402-ab16f280-e429-11e8-96be-231abdd314ab.png)

**Comment by eliodilar** [comment] 2018-11-09 14:47
Fist step Remove E- from @sed cmd.

a new error with sed cmd in compiler ( for me 4.2 and 4.1) sed lib install on amd64
![sed 2](https://user-images.githubusercontent.com/44893881/48269007-d05e2d80-e436-11e8-97ba-89aab5cd3e8c.png)

**Comment by eliodilar** [comment] 2018-11-09 15:05
Makefile caph-source
docman commentary

ifeq ($(BUILD_DOC), yes)
	(cd man; $(MAKE) all)
	#(cd doc; $(MAKE) all)

**Comment by eliodilar** [comment] 2018-11-09 15:06
qt4 lib not instal to view later

**Comment by jserot** [comment] 2018-11-11 10:51
Seems the problem is the version of the sed command.
I cannot reproduce it on my Linux test platform (LinuxMint).
Will test on on Ubuntu ASAP.
Meanwhile, a workaround is to disable the build of documentation by passing the [--no-doc] flag to the [configure] script.

**Comment by eliodilar** [comment] 2018-11-12 08:08
What kind of sed version have you , i have try with 4.1 and 4.2.

**Comment by eliodilar** [comment] 2018-11-12 08:16
please, give the location of the Makefile and the line of the instruction to change cordially.

**Comment by eliodilar** [comment] 2018-11-12 08:56
hie, your sed version is an amd 64 or i386 processor?

**Comment by jserot** [comment] 2018-11-12 10:28
The first problem is indeed caused by the  -E option of the sed command (it is a non standard FreeBSD extension). It is solved by rewriting line 38 of man/Makefile :

	@sed -E -e "s/\\\\label{[^}]+}|\\\\index{[^}]+}//g" -e "s/section/section*/" $@ > _$@
as
	@sed -e "s/\\\\label{[^}]+}|\\\\index{[^}]+}//g" -e "s/section/section*/" $@ > _$@

I cannot understand the second one; 
Can you be more precise (and open a separate issue please) ?

**Comment by eliodilar** [comment] 2018-11-12 10:36
yep also the same probleme on latex , the shell shutdown at that line.
I desctivate #(cd doc; $(MAKE) all) because there is to mutch problem.

![latex sed](https://user-images.githubusercontent.com/44893881/48342110-23222a00-e66f-11e8-838b-7bd43e96c55f.png)

**Comment by jserot** [comment] 2018-11-12 10:50
Building the documentation from the .tex sources requires the `pdlatex` command.

**Comment by eliodilar** [comment] 2018-11-12 12:49
Tex Live and and all languages and caractèrs libs are install...
I see that it's caph-lrm > pdftex.log who crash , there is some caph Data flow adaptation inside the document, i think there is problem hear.

this is that line  of lrm compilator who make crash
#pdflatex $(DOC).tex > pdflatex.log

**Comment by jserot** [comment] 2018-11-13 10:24
May i suggest that you use the pre-compiled PDF documentation available on the web site.
It is difficult to fix the problem the report because it may be related to your local TeX installation.

Also, please open separate issues for reporting separate problems.

The problem with the `sed` command is fixed in v2.9.0

**Comment by eliodilar** [comment] 2018-11-13 12:23
#pdflatex$(doc).tex > pdfLatex.log commented

**Closed as completed** 2018-11-13 12:23 UTC
